language: python

python:
    - "2.7"

install:
    - pip install --upgrade pip setuptools wheel
    - pip install --only-binary=numpy,scipy numpy scipy
    - python setup.py develop
    - pip install -r dev-requirements.txt

script: pytest

