language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"

install:
    - pip install -r dev-requirements.txt
    - pip install tox-travis coveralls

script:
    - flake8
    - tox -- --timeout=60 --verbose --verbose

after_success:
    - coveralls

